# comment with #

key-1="value 1" # trailing comment
# space around key and value
  key_2  =  "value 2"
# tab around key and value
  key_3 = "value 3"

# basic strings
basic-empty = ""
basic-contains-escapes = "\"value\\\""
basic-contains-comment = "# comment" # comment

# literal strings
literal = 'value'
literal-empty = ''
literal-contains-escapes = '"value"\'
literal-contains-comment = '# comment' # comment

# ints
int-1 = 0
int-2 = 12

# booleans
boolean-1 = true
boolean-2 = false

# dotted paths
table.key = "value"
table.nested.key = "value"

table-2.key = "value"

# out of order
table.key-2 = "value"

# implicit intermediate table
table-3.nested.nested.nested.key = "value"

# tables
[header]
key = "value"

# table is already defined
[table.nested-2]
key = "value"

# no trailing new line